In [1]:
#	데이터	분석	툴
import	pandas	as	pd
import	numpy	as	np
#	운영체계와	관련된	툴
import	os
import	glob
#	시각화	
import	seaborn	as	sns
import	matplotlib.pyplot	as	plt	#	matplotlib


#	경고	방지
import	warnings	#	워닝	방지
warnings.filterwarnings('ignore')

In [2]:
#현재	위치
os.getcwd()

'C:\\IT\\workspace_python\\프로젝트2'

In [3]:
import duckdb

query = """
    SELECT * FROM read_csv_auto('./dataset_18/5공정_180sec/*.csv')
"""

con = duckdb.connect()
tbl = con.execute(query).df()

In [4]:
tbl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51084 entries, 0 to 51083
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Index    51084 non-null  int64
 1   Process  51084 non-null  int64
 2   Time     51084 non-null  object
 3   Temp     51084 non-null  float64
 4   Current  51084 non-null  float64
 5   Date     51084 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), object(1)
memory usage: 2.3+ MB

In [5]:
tbl.head()

   Index  Process          Time       Temp  Current       Date
0      1        1  오후 4:24:03.0  75.139142    1.610 2021-09-06
1      2        1  오후 4:24:08.0  76.660421    1.530 2021-09-06
2      3        1  오후 4:24:13.0  77.177660    1.701 2021-09-06
3      4        1  오후 4:24:18.0  76.586434    1.736 2021-09-06
4      5        1  오후 4:24:23.0  77.877104    1.748 2021-09-06

In [6]:
query = """
    SELECT
        *,
        strptime(
            printf('%s %s', 
                strftime(Date::TIMESTAMP, '%Y-%m-%d'),
                replace(replace(Time, '오전', 'AM'), '오후', 'PM')
            ),
            '%Y-%m-%d %p %I:%M:%S.%g'
        ) AS Datetime
    FROM tbl
"""

con = duckdb.connect()
tbl2 = con.execute(query).df()
print(tbl2[['Date', 'Time', 'Datetime']].head())

        Date          Time            Datetime
0 2021-09-06  오후 4:24:03.0 2021-09-06 16:24:03
1 2021-09-06  오후 4:24:08.0 2021-09-06 16:24:08
2 2021-09-06  오후 4:24:13.0 2021-09-06 16:24:13
3 2021-09-06  오후 4:24:18.0 2021-09-06 16:24:18
4 2021-09-06  오후 4:24:23.0 2021-09-06 16:24:23

In [7]:
tbl2.head()

,Index,Process,Time,Temp,Current,Date,Datetime
0,1,1,오후 4:24:03.0,75.139142,1.610,2021-09-06,2021-09-06 16:24:03
1,2,1,오후 4:24:08.0,76.660421,1.530,2021-09-06,2021-09-06 16:24:08
2,3,1,오후 4:24:13.0,77.177660,1.701,2021-09-06,2021-09-06 16:24:13
3,4,1,오후 4:24:18.0,76.586434,1.736,2021-09-06,2021-09-06 16:24:18
4,5,1,오후 4:24:23.0,77.877104,1.748,2021-09-06,2021-09-06 16:24:23

In [8]:
tbl2 = tbl2.drop(['Time', 'Date', 'Index'], axis=1)

In [9]:
tbl2.head()

   Process       Temp  Current            Datetime
0        1  75.139142    1.610 2021-09-06 16:24:03
1        1  76.660421    1.530 2021-09-06 16:24:08
2        1  77.177660    1.701 2021-09-06 16:24:13
3        1  76.586434    1.736 2021-09-06 16:24:18
4        1  77.877104    1.748 2021-09-06 16:24:23

In [10]:
tbl2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51084 entries, 0 to 51083
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Process   51084 non-null  int64
 1   Temp      51084 non-null  float64
 2   Current   51084 non-null  float64
 3   Datetime  51084 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1)
memory usage: 1.6 MB